--- 
:backgroundrb: 
  :ip: localhost
  :port: 11011
  :environment: production
  
:schedules:
 :monitoring_worker:
  :hotspots_monitoring:
   :trigger_args: 0  */5  *  * * *
  :consolidate:
   :trigger_args: 0   0  */1 * * *
  :housekeeping:
   :trigger_args: 0  30   2  1 * *
