defaults: &defaults
  showmap: false
  last_logins: true
  # values should be between 1 and 100
  access_point_pagination: [
    { value: 10, default: false },
    { value: 20, default: false },
    { value: 50, default: false },
    { value: 100, default: true }
  ]
  showstatus: false        # show status column in availability report

  # Number of threads
  max_threads: 10
  # Minutes between pings
  ping_timeout: 5
  # Months for the housekeeping
  housekeeping_interval: 6
  
  # host for links sent via email
  protocol: https
  host: change_me.com
  # from email in alerts and exception reports
  from_email: owgm@localhost
  
  # default value for group setting "alert_threshold_up"
  alerts_threshold_down:  90
  # default value for group setting "alert_threshold_up"
  alerts_threshold_up:  45
  # default value for group setting "alert_email"
  alerts_email: ""

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
